# Generated by Django 5.0 on 2023-12-14 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='status',
            field=models.IntegerField(default=1),
        ),
    ]
